# -*- coding: utf-8 -*-
"""Document.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTah1Z2Y6kG8igUbj5XKFft1JFpcUkv_
"""

import requests,os
import time
from dotenv import load_dotenv

load_dotenv()

endpoint ="https://shruti-docu.cognitiveservices.azure.com/"
key = "key"

url = endpoint + "formrecognizer/documentModels/prebuilt-invoice:analyze?api-version=2023-07-31"


headers = {
    "Ocp-Apim-Subscription-Key": key,
    "Content-Type": "image/jpeg"
}

# step 1: send invoice
with open("invoice.png", "rb") as f:
    data = f.read()

response = requests.post(url, headers=headers, data=data)

print("Step 1 Status:", response.status_code)
print("Headers:", response.headers)

# check if request accepted
if response.status_code == 202:

    result_url = response.headers["operation-location"]

    # wait for processing
    time.sleep(5)

    # step 2: get result
    result = requests.get(result_url,
                          headers={"Ocp-Apim-Subscription-Key": key})

    print("Final Result:")
    print(result.json())

else:
    print("Error:")
    print(response.text)